### ISSUE TITLE
The Bot replaces emotes that it shouldn't

### ISSUE THREAD

**Issue by Levev** [ExAtom/GroundedBot#3]
# When using the standard subscription
The bot replaces emotes that are in the server too. Therefore, because the standard subscription does not allow placing emotes inside sentences, it removes them. This can be annoying sometimes.

The message:
```
this was funny :kekw:
```
gets replaced by:
```
:kekw:
```

**Comment by ExAtom** [comment]
Fixed in the latest version. Thanks for the issue report
